curl -u Semintra:api_key https://api.github.com/users/ta-data-pt-rmt/repos?page=1&per_page=100

curl -u Senimtra:api_key https://api.github.com/repos/ta-data-pt-rmt/lab-mysql-first-queries/forks?page=1&per_page=100